=== luisoi1993/curso2019-2020/curso_2019_2020/curso_2019_2020/html/ejercicios camaradas/Lenguaje de Marcas/XML/XML-DTD/Ejercicio1/ejercicio1.dtd
<!DOCTYPE cartelera[
    <!ELEMENT cartelera(pelicula*)>
    <!ELEMENT pelicula(titulo, (titulo_original)?, nacionalidad, genero, clasificación, sinopsis, director,(reparto)+,web,cartel)*>
            <!ATTLIST pelicula codigo ID #REQUIERED>
            <!ATTLIST pelicula duración NMTOKEN #REQUIERED>
            <!ATTLIST pelicula año NMTOKEN="2003" #IMPLIED>
        <!ELEMENT titulo (#PCDATA)*>
        <!ELEMENT titulo_original (#PCDATA)>
        <!ELEMENT nacionalidad (#PCDATA)>
        <!ELEMENT genero (#PCDATA)>
        <!ELEMENT clasificación (#PCDATA)>
            <!ATTLIST clasificación CDATA #IMPLIED>
        <!ELEMENT sinopsis (#PCDATA)>
        <!ELEMENT director (#PCDATA)>
        <!ELEMENT reparto (#PCDATA)>
        <!ELEMENT web (#PCDATA)>
        <!ELEMENT cartel (#PCDATA)>
    <!ELEMENT reparto(actor)*>
        <!ELEMENT actor (#PCDATA)*>
]>

=== luisoi1993/curso2019-2020/curso_2019_2020/curso_2019_2020/html/ejercicios camaradas/Lenguaje de Marcas/XML/XML-DTD/Ejercicio1/ejercicio1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="ejercicio1.css"?>

<!--
                    DTD EXTERNA 
    <!DOCTYPE cartelera SYSTEM "ejercicio1.dtd">    
-->

<!DOCTYPE pelicula[
    <!ELEMENT pelicula (titulo, titulo_original, nacionalidad, genero, clasificación, sinopsis, director,reparto,web,cartel)*>
            <!ATTLIST pelicula codigo NMTOKEN '#REQUIERED'>
            <!ATTLIST pelicula duración NMTOKEN '#REQUIERED'>
            <!ATTLIST pelicula año NMTOKEN '#IMPLIED'>
        <!ELEMENT titulo (#PCDATA)*>
        <!ELEMENT titulo_original (#PCDATA)>
        <!ELEMENT nacionalidad (#PCDATA)>
        <!ELEMENT genero (#PCDATA)>
        <!ELEMENT clasificación (#PCDATA)>
            <!ATTLIST clasificación edad NMTOKEN '#IMPLIED'>
        <!ELEMENT sinopsis (#PCDATA)>
        <!ELEMENT director (#PCDATA)>
        <!ELEMENT reparto (#PCDATA)>
        <!ELEMENT web (#PCDATA)>
        <!ELEMENT cartel (#PCDATA)>
    <!ELEMENT reparto (actor)*>
        <!ELEMENT actor (#PCDATA)*>
]>

<cartelera>
    <pelicula código="p1" duración="152" año="2002">
        <titulo>AQUELLAS JUERGAS UNIVERSITARIAS</titulo>
        <titulo_original>Old School</titulo_original>
        <nacionalidad>Estados Unidos</nacionalidad>
        <genero>Comedia</genero>
        <clasificación edad="tp"/>
        <sinopsis>
            Mitch, Frank y Beanie son tres amigos treintañeros cuyas vidas no son exactamente lo que
            esperaban. Mitch tiene una novia ninfómana que se mete en la cama con el primero que agarra.
            Frank se ha casado y su matrimonio nada
            tiene que ver con las juergas salvajes que organizaban años atrás. Y Beanie es
            un padre de familia que se muere por recuperar su alocada juventud. Pero las cosas cambian
            cuando Beanie sugiere que creen su propia fraternidad, en la nueva casa que Mitch tiene junto
            al campus de la universidad. Una ocasión para revivir tiempos gloriosos, hacer nuevos amigos
            y de volver a sus viejas, salvajes y desmadradas juergas de estudiantes.
        </sinopsis>
        <director>Todd Philips</director>
        <reparto>
            <actor>Luke Wilson</actor>
            <actor>Will Farrel</actor>
            <actor>Vince Vaughn</actor>
        </reparto>
        <web>http://www.uip.es</web>
        <cartel>caratulas/Aquellas juergas.jpg</cartel>
    </pelicula>

    <pelicula código="p17" duración="06">
        <titulo>EL ORO DE MOSCÚ</titulo>
        <nacionalidad>España</nacionalidad>
        <genero>Comedia</genero>
        <sin_clasificar/>
        <sinopsis>
            Por una extraña coincidencia del destino, alguien recibe una información extraconfidencial de
            un anciano en sus últimos segundos de vida: el secreto mejor guardado de la Historia. El
            receptor, un trabajador de hospital, se lo comunica secretamente a un supuesto amigo. Ambos
            inician una aventura rocambolesca y llena de misterio. Ante la inutilidad de sus intentos y muy
            a
            su pesar, tienen que recurrir a otras personas que así mismo van cayendo en el pozo sin fondo
            que conlleva descifrar el enigma.
        </sinopsis>
        <director>Jesús Bonilla</director> 
        <reparto>
            <actor>Jesús Bonilla</actor>
            <actor>Santiago Segura</actor>
            <actor>Alfredo Landa</actor>
            <actor>Concha Velasco</actor>
            <actor>Antonio Resines</actor>
            <actor>Gabino Diego, María Barranco</actor>
            <actor>María Barranco</actor>
        </reparto>
    </pelicula>
</cartelera>
