<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE operaciones [
<!ELEMENT  operaciones (operacion)*>
<!ELEMENT operacion ((venta|compra),(compra|venta))+>
<!ELEMENT venta (titulosvendidos+,titulo+,cantidadtotal,entregado?,importe+)>
<!ELEMENT compra (tituloscomprados+,titulo*,proveedor+,fechacompra+)>
<!ELEMENT fechacompra (dia+,mes+,anio+)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT cantidadtotal (#PCDATA)>
<!ELEMENT importe (#PCDATA)>
<!ELEMENT entregado EMPTY>
<!ELEMENT proveedor (#PCDATA)>
<!ELEMENT dia (#PCDATA)>
<!ELEMENT mes (#PCDATA)>
<!ELEMENT anio (#PCDATA)>
<!ATTLIST importe moneda CDATA #REQUIRED>
]>

<operaciones>
 <operacion>
 
 
 <venta>
 <titulosvendidos>
 <titulo>Don Quijote</titulo>
 <titulo>Rimas y leyendas</titulo>
 <cantidadtotal>2000</cantidadtotal>
 <importe moneda="euros">4400</importe>
 </titulosvendidos>
 </venta>
 
 <venta>
 <titulosvendidos>
 <titulo>Rinconete y Cortadillo</titulo>
 <titulo>Sainetes</titulo>
 <cantidadtotal>1000</cantidadtotal>
 <entregado/>
 <importe moneda="libras">290</importe>
 </titulosvendidos>
 </venta>
 
 </operacion>
 
 
 <operacion>
 
 <compra>
 <tituloscomprados>
 <titulo>De la Tierra a la Luna</titulo>
 <titulo>Barbarroja</titulo>
 <proveedor>Editorial EDSA</proveedor>
 <fechacompra>
 <dia>10</dia>
 <mes>6</mes>
 <anio>2018</anio>
 </fechacompra>
 </tituloscomprados>
 </compra>
 
 
 <venta>
 <titulosvendidos>
 <titulo>Cinco semanas en globo</titulo>
 <titulo>Sainetes</titulo>
 <cantidadtotal>700</cantidadtotal>
 <entregado/>
 <importe moneda="euros">1490</importe>
 </titulosvendidos>
 </venta>
 
 
 <compra>
 <tituloscomprados>
 <titulo>De la Tierra a la Luna</titulo>
 <titulo>Barbarroja</titulo>
 <proveedor>Editorial Recopila</proveedor>
 <fechacompra>
 <dia>2</dia>
 <mes>12</mes>
 <anio>2017</anio>
 </fechacompra>
 </tituloscomprados>
 </compra>
 
 
 </operacion>
 
 
 
</operaciones>


















